CREATE DATABASE IF NOT EXISTS rehabia CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'cesar'@'localhost' IDENTIFIED BY 'cesar123';
GRANT ALL PRIVILEGES ON rehabia.* TO 'cesar'@'localhost';
FLUSH PRIVILEGES;
